### PR TITLE
Prevent minimist from coercing strings to numbers

### PR DESCRIPTION
**Pull request by hsablonniere**

### CODE REVIEW

**Comment by divarvel** [comment]
LGTM (waiting for the tests to pass).
Thinking about it we could disable minimist auto parsing for everything, and have parsers reliably work on strings (maybe for another PR).

**Comment by hsablonniere** [comment]
Hum, interesting... I guess it makes sense. It would mean forcing everything to be a string, right?

**Comment by hsablonniere** [comment]
Build failed because of nvm?

**Comment by divarvel** [comment]
Yes, that would mean parsing everything from strings. IIRC the existing parsers already handle strings.

**Comment by divarvel** [comment]
I prefer that because you can provide parsers, so explicitely testing for the stringparser would not be sufficient

**Comment by divarvel** [comment]
That would only require a modification to boolean parsers, as everything else is already handling strings correctly

**Comment by hsablonniere** [comment]
So we're talking about that?

* renaming the commit to something like "force minimist to treat everything as a string"
* modifiying this to handle strings https://github.com/divarvel/cliparse-node/blob/master/src/parsers.js#L27

**Comment by divarvel** [comment]
Yep, exactly

**Comment by hsablonniere** [comment]
I did a deeper analysis. Doing what we described means we're not relying on minimist code and logic to detect boolean which you can find in this loop: https://github.com/substack/minimist/blob/master/index.js#L94

We'll have to consider this behaviour from minimist:

* empty string `""` => true
* undefined `undefined` => false

Do we want to support explicit true/false like `mycommand --myarg true`. I guess not since the purpose of a flag is to be implicit.

**Comment by hsablonniere** [comment]
This also means we won't need this cleanup anymore: https://github.com/divarvel/cliparse-node/blob/master/src/cli.js#L140-L145

**Comment by divarvel** [comment]
+1 for not supporting `--myarg true`, great if it allows us to remove code

On Wed, Jan 3, 2018 at 4:25 PM, Hubert SABLONNIÈRE <notifications@github.com

**Comment by hsablonniere** [comment]
If you do `clever activity --show-all false` it displays:

```
show-all: invalid boolean: false
```
Same for true. It's a bit odd, isn't it?

**Comment by hsablonniere** [comment]
So forcing minimist to handle everything means we now only accept empty string or undefined for boolean values. I had to update the tests in a few places and clearly it feels odd. WDYT?

**Comment by divarvel** [comment]
So either:

 - we mimic exactly minimist's behaviour for booleans
 - we mark flags as boolean args when calling minimist, and string for everything else

I prefer the second solution

**Comment by hsablonniere** [comment]
> we mark flags as boolean args when calling minimist, and string for everything else

I went for this solution and it's now building/testing on Travis!

**Comment by divarvel** [comment]
Thanks a lot! It will remove strange corner cases \o/

**Pull request merged**
