### PR TITLE
[Completion] Prevent minimist from coercing strings to numbers

### PR DESCRIPTION
**Pull request by judu**
This fixes the error I get when the word I want to complete starts with digits.

Example:

The words I want to complete are uuids. Like 06b56181-cce5-4f9f-9ebf-d33683dd5796.

Before my PR :

```
/…/test $ ./test show 06<tab>
test/node_modules/cliparse/src/autocomplete.js:96
    } else if(word.slice(0,1) === '-') {
                   ^

TypeError: word.slice is not a function
    at test/node_modules/cliparse/src/autocomplete.js:96:20
    at arrayReduce (test/node_modules/lodash/lodash.js:683:21)
    at Function.reduce (test/node_modules/lodash/lodash.js:9683:14)
    at Object.autocomplete.currentArg (test/node_modules/cliparse/src/autocomplete.js:75:22)
    at Object.cli.autocomplete (test/node_modules/cliparse/src/cli.js:98:35)
    at Object.cli.parse (test/node_modules/cliparse/src/cli.js:160:9)
    at Object.<anonymous> (test/supernova.js:726:10)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:774:12)
    at executeUserCode (internal/bootstrap/node.js:342:17)
    at startExecution (internal/bootstrap/node.js:276:5)
    at startup (internal/bootstrap/node.js:227:5)
```

With my PR:

```
/…/test $ ./test show 06<tab>
06b56181-cce5-4f9f-9ebf-d33683dd5796
```

### CODE REVIEW

**Comment by judu** [comment]
Btw, reading your answer to @jtanguy, you seem to wish to drop the ownership of cliparse-node. We are open to assume the ownership of it, if you want to!

**Comment by divarvel** [comment]
Thanks for your PR! I've stopped using this lib indeed, so I'd gladly transfer ownership to you (especially since you're its biggest user).

**Comment by judu** [comment]
Alright, you can transfer it to the CleverCloud organisation, since I'm not going to be the only one maintaining it. That is, if you are ok with it!

**Comment by divarvel** [comment]
I've moved the discussion here: https://github.com/divarvel/cliparse-node/issues/24

I can't transfer ownership as I am not allowed to create repos in the clever cloud org

**Pull request merged**
